FROM php:8.2.20-apache-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    unzip && \
    a2enmod rewrite && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY . /var/www/html/
EXPOSE 80
